### ISSUE TITLE
Question about Nardo-Air datasets

### ISSUE THREAD

**Issue by euncheolChoi** [AnyLoc/AnyLoc#1]
Thanks for sharing your great work. This isn't a question about AnyLoc, but I'd like to know how you were able to access the Nardo-Air dataset you used for testing. 
I couldn't find an access link when I googled it, is there any chance you could shed some light on that?

Thanks in advance.

**Comment by JayKarhade** [comment]
Hi @euncheolChoi , the Nardo-Air dataset was collected by members of our lab, and they haven't made it publicly available yet. That would be the reason why you cannot access any link.

**Comment by euncheolChoi** [comment]
Oh I see, then do you plan to share this dataset as a public one in the future?

**Comment by shockwaveHe** [comment]
Hi @euncheolChoi, me and another guy in the lab collect the dataset. The Nardo-Air dataset is primarily used for another project. Idealy it will be release when we decide to submit the paper for that project, probably ICRA2024. By the time I will inform you.

**Comment by euncheolChoi** [comment]
Thank you, and I look forward to seeing it as a public dataset soon !

**Comment by JayKarhade** [comment]
Closing this for now :)

**Comment by TheProjectsGuy** [comment]
Update: included the datasets in the [public release](https://github.com/AnyLoc/AnyLoc#included-datasets)
