### ISSUE TITLE
Question about MSLS

### ISSUE THREAD

**Issue by Graysonggg** [AnyLoc/AnyLoc#10]
Great work!
May I ask why MSLS dataset is not used in your paper?  Will you use it in future work?

**Comment by JayKarhade** [comment]
Hi @1994225000kk , we believe the datasets evaluated capture a good representative of our performance improvements and method's universal capabilities . We may consider benchmarking scores on MSLS data in the future, but do not have immediate plans as of now.  

Closing this issue for now :), feel free to reopen in case anything is unanswered
