### ISSUE TITLE
AnyLoc-VLAD-DINO : "ViT-S8 layer 9 key facet features and 128 clusters for VLAD."

### ISSUE THREAD

**Issue by Waycn** [AnyLoc/AnyLoc#12]
if use "AnyLoc-VLAD-DINO",how to load model and  download vocabulary?
![2023-10-10 18-14-56屏幕截图](https://github.com/AnyLoc/AnyLoc/assets/46624784/3142b0c3-b87a-4f07-98aa-c1ae32748857)
![2023-10-09 10-25-33屏幕截图](https://github.com/AnyLoc/AnyLoc/assets/46624784/8345745a-3d53-44f7-8eef-cad7c051c5d1)

**Comment by TheProjectsGuy** [comment]
Hey @Waycn, thanks for taking an interest in our work.

## AnyLoc-VLAD-DINO

If you insist on using AnyLoc-VLAD-DINO (using features from DINOv1, **not** DINOv2), we haven't created a simple demo script to extract VLAD descriptors from a set of images. You can see some files that could help

- [dino_global_vocab_vlad.py](https://github.com/AnyLoc/AnyLoc/blob/main/scripts/dino_global_vocab_vlad.py): VLAD with cluster centers obtained from a set of datasets. You'll need to download the datasets and wait for the program to generate the cache files. A sample command can be found by referring to the [ablations](https://github.com/AnyLoc/AnyLoc/blob/main/scripts/dino_global_vocab_vlad_ablations.sh).
- [dino_extractor.py](https://github.com/AnyLoc/AnyLoc/blob/main/dino_extractor.py): The wrapper for extracting ViT features from DINOv1 is in class `ViTExtractor`. This is similar to `DinoV2ExtractFeatures` for DINOv2 (see section on DINOv2 below).

Note for #7: We can consider this for a future release.

In the meantime, I suggest you use DINOv2 (the better-performing variant) included in our demos.

## AnyLoc-VLAD-DINOv2

As you highlighted in your [first image](https://user-images.githubusercontent.com/46624784/273863544-3142b0c3-b87a-4f07-98aa-c1ae32748857.png), you can load the model from scratch (using `torch.hub`). However, as done in our [demo to extract global descriptors](https://github.com/AnyLoc/AnyLoc/blob/main/demo/anyloc_vlad_generate_colab.ipynb), I suggest you use our `DinoV2ExtractFeatures` class from [utilities.py](https://github.com/AnyLoc/AnyLoc/blob/main/demo/utilities.py). This will allow you to extract features from any facet of any block/layer in the ViT. AnyLoc-VLAD-DINOv2 uses ViT-G/14, layer 31, `value` facet. 

We provide a VLAD class in our utilities, you'll need to download the vocabulary (as you have already done in [image 2](https://user-images.githubusercontent.com/46624784/273863707-8345745a-3d53-44f7-8eef-cad7c051c5d1.png)). As long as the [cluster centers file is found](https://github.com/AnyLoc/AnyLoc/blob/063c75de5c62e0163ab65f602dab6784a898c464/demo/anyloc_vlad_generate.py#L145), the script should automatically detect it and allow you to generate VLAD (global/image) descriptors using the cached vocabulary.

Hope this helps clarify your doubts, let me know if there are any further issues.
