### ISSUE TITLE
need help when run  run the cmd python  dino_v2_vlad.py  on terminal 

### ISSUE THREAD

**Issue by YunLi-AI** [AnyLoc/AnyLoc#15]
there is an error 
I add print(db_vlads) in  script->dino_v2_vlad.py  row of  368th 

whilch show tensor([NAN]) after run the cmd python  dino_v2_vlad.py  on terminal 

when I modify  script->dino_v2_vlad.py row of  93th  desc_facet: Literal["query", "key", "value", "token"] = "query" or "value"
     and modify anyloc (main directory)-> config.py row of 82th vg_dataset_name = "st_lucia"

the dataset download from the onedriver mentioned in the readme.md

tree ./st_lucia is
```
./st_lucia
|-- [  26]  images
|   `-- [  49]  test
|       |-- [148K]  database [1549 entries exceeds filelimit, not opening dir]
|       `-- [140K]  queries [1464 entries exceeds filelimit, not opening dir]
`-- [695K]  map_st_lucia.png
```
I would greatly appreciate it if you could reply

**Comment by YunLi-AI** [comment]
It's strange that I didn't change anything and the problem disappeared. Currently, all the results are normal. I am very sorry for the inconvenience caused to you

**Comment by TheProjectsGuy** [comment]
No problem. Closing the issue for now. Feel free to reply if you face any issues.
