### ISSUE TITLE
About GT.npy of the datasets in the paper

### ISSUE THREAD

**Issue by MAX-OTW** [AnyLoc/AnyLoc#17]
Hello, @TheProjectsGuy ,thank you very much for your great work！
At present, the GT.npy of the datasets in the repo is not very clear for me to understand.
Can you provide GT.npy for all datasets? They are in the format of the Gardens Point dataset, or can you provide scripts for other datasets that generate GT.npy similar to Gardens Point? (Such GT.npy can reflect the relationship between the query and the ref, that is, one query corresponds to several refs ).

Hope to receive your reply soon :)
Thanks & Best Regards!

**Comment by TheProjectsGuy** [comment]
Hey @MAX-OTW,

Thanks for taking an interest in our work. The `.npy` files for other datasets are available in our [Public Release](https://iiitaphyd-my.sharepoint.com/:f:/g/personal/robotics_iiit_ac_in/EtpBLzBFfqdHljqQMnm6xdoBzW-4KFLXieXDVN4vPg84Lg?e=BP6ZW1) (the `Datasets-All` folder has `.tar.gz` files that contains these files along with the datasets).

I request you refer to [this comment](https://github.com/AnyLoc/AnyLoc/issues/8#issuecomment-1712450557) for these files. They're basically for replicating the work and not really for the end user (who would want to extract global descriptors).

Let me know if the discussion in #8 doesn't fulfill your queries.
