### ISSUE TITLE
Conda environment installation error

### ISSUE THREAD

**Issue by Mui33** [AnyLoc/AnyLoc#21]
Hi,
I am installing the environment via [setup_conda.sh](https://github.com/AnyLoc/AnyLoc/blob/main/setup_conda.sh) and when I run to the code `conda install -y -c pytorch faiss-gpu==1.7.2`, the following error is reported: 
```
Collecting package metadata (current_repodata.json): done                       
Solving environment: failed with initial frozen solve. Retrying with flexible solve.                                                                            
Collecting package metadata (repodata.json): done                               
Solving environment: failed with initial frozen solve. Retrying with flexible solve.                                                                            
Solving environment: \                                                          
Found conflicts! Looking for incompatible packages.                             
This can take several minutes.  Press CTRL-C to abort.                          
failed                                                                          
                                                                                
UnsatisfiableError: The following specifications were found                     
to be incompatible with the existing python installation in your environment:   
                                                                                
Specifications:                                                                 
                                                                                
  - faiss-gpu==1.7.2 -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']                                                                          
                      
Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - faiss-gpu==1.7.2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python=3.9 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35
```
And when I install via `conda install -c conda-forge faiss-gpu=1.7.2`, the above error does not occur, but it installs a second cuda in my environment as follows:
```
The following packages will be downloaded.

    package | build
    ---------------------------|-----------------
    cudatoolkit-11.8.0 | h4ba93d1_12 682.8 MB conda-forge
    faiss-1.7.2 |py39cuda112h460e57a_4_cuda 1.2 MB conda-forge
    faiss-gpu-1.7.2 | h788eb59_4 15 KB conda-forge
    libfaiss-1.7.2 |cuda112hb18a002_4_cuda 51.4 MB conda-forge
    libfaiss-avx2-1.7.2 |cuda112h1234567_4_cuda 51.4 MB conda-forge
```
Here's part of my conda list:
```
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cudatoolkit               11.8.0              h4ba93d1_12    conda-forge
```
How do I install packages so that my environment doesn't conflict?

**Comment by TheProjectsGuy** [comment]
Hey @Mui33,

Are you trying to replicate our work or only use the AnyLoc method for estimating global descriptors?

## Estimating Global Descriptors

I'd suggest you check out the [demos](https://github.com/AnyLoc/AnyLoc/tree/main/demo) in this case. It contains [a script](https://github.com/AnyLoc/AnyLoc/blob/main/demo/anyloc_vlad_generate.py) (and [a Colab notebook](https://github.com/AnyLoc/AnyLoc/blob/main/demo/anyloc_vlad_generate_colab.ipynb)) to do just the same.

In fact, you can now also use `torch.hub` for doing this. See [this comment](https://github.com/AnyLoc/AnyLoc/issues/11#issuecomment-1783870144) for more information. It has the following dependencies

```py
dependencies = [
    'torch', 'torchvision',     # Basic PyTorch
    'einops',       # Functionalities (utilities)
    'fast_pytorch_kmeans', # KMeans clustering (in VLAD)
]
```

You can install them using `conda`, `mamba`, or even `pip` (however you choose). This is going to be our preferred way of using AnyLoc.

## Replicating our work

Though the [Getting Started README](https://github.com/AnyLoc/AnyLoc/tree/2ae462dbce05a2741fe8d075a1313488804e29a3#getting-started) suggests that `You can also use an existing conda environment`, I suggest you use a separate environment for this purpose (to avoid any conflicts with already installed packages).

Let me know if I have answered your concerns.

On a side note (for future reference), our installer runs this

https://github.com/AnyLoc/AnyLoc/blob/2ae462dbce05a2741fe8d075a1313488804e29a3/setup_conda.sh#L222

**Comment by TheProjectsGuy** [comment]
Just saw that it downloads a separate `cudatoolkit` (11.8)
![image](https://github.com/AnyLoc/AnyLoc/assets/29420733/17afaf9b-bb8c-4cbe-b71b-503299949347)

This doesn't seem interfere with the CUDA toolkit for PyTorch (for our versions at least)
![image](https://github.com/AnyLoc/AnyLoc/assets/29420733/dce5b8fc-99b2-4ff1-b338-5eea652c64ac)

The CUDA conflict causes no problems running scripts in AnyLoc on our end.

**Comment by Mui33** [comment]
Yes, I'm trying to replicate your work. Thank you for your validation and answers! @TheProjectsGuy 

Since I had other reported errors during my replication, I've been worried that maybe a conda environment conflict was causing the error. Thank you for helping me to eliminate this concern.

Maybe you guys could modify the installation code for the faiss package. Because the code  `conda_raw_install -c pytorch faiss-gpu==1.7.2 ` does not install the package correctly.
