### ISSUE TITLE
Distance used for query (image retrieval)

### ISSUE THREAD

**Issue by BrianG13** [AnyLoc/AnyLoc#25]
Thanks for sharing your work! The paper is very interesting and this repo looks extremely good and detailed.

I have a question that I couldn't find the answer in the paper.

I see there are several option for an image descriptor:
- DinoV2 CLS token
- GeM pooling over DINOv2 ViT features
- VLAD over DINOv2 ViT feature

My question is:
For each one of these descriptors.. what is the distance you used for image retrieval (to fetch the most relevant image in dataset).
Cosine distance? L2 distance?

**Comment by TheProjectsGuy** [comment]
Hey there,

Thanks for your interest in our work. We use the cosine distance for retrieval. You can verify this using the function calls to `get_top_k_recall` (like in the DINOv2)

https://github.com/AnyLoc/AnyLoc/blob/f69501e0c9f80648483ac4e95c06b194642459a5/scripts/dino_v2_global_vocab_vlad.py#L550-L555

The default value for `method` is `"cosine"`

https://github.com/AnyLoc/AnyLoc/blob/f69501e0c9f80648483ac4e95c06b194642459a5/utilities.py#L390

However, the descriptors are normalized before computing the distances as you can see here

https://github.com/AnyLoc/AnyLoc/blob/f69501e0c9f80648483ac4e95c06b194642459a5/utilities.py#L435-L437
