### ISSUE TITLE
Question about SAM

### ISSUE THREAD

**Issue by Graysonggg** [AnyLoc/AnyLoc#27]
Amazing job! 

I noticed that in addition to dino, you also tried other fundamental models such as sam and clip, and sam's model selection is reflected in the following two lines in the document:
https://github.com/AnyLoc/AnyLoc/blob/a9fda68c55083f765b019df148a1b67614f90ee2/scripts/SAM_many.sh#L13
https://github.com/AnyLoc/AnyLoc/blob/a9fda68c55083f765b019df148a1b67614f90ee2/scripts/SAM_many.sh#L14
https://github.com/AnyLoc/AnyLoc/blob/a9fda68c55083f765b019df148a1b67614f90ee2/scripts/SAM_many.sh#L17

I'm curious about that what is the consideration behind these choices?   Why isn't the cluster center set to 32 like dinov2?   And have you considered to use larger sam  ​like sam-vit-L?

Looking forward to your reply.

**Comment by JayKarhade** [comment]
Hi @Graysonggg we had done preliminary evaluations on SAM with those parameters, however we did not see better performance than DINOv2 and hence didn't probe further. 

The hyperparameters that have been used are just an artifact of those evaluations. We did benchmark against bigger ViT models too, but didn't see much difference.
