### ISSUE TITLE
would you release the vlad paramter in the paper?

### ISSUE THREAD

**Issue by ghoshaw** [AnyLoc/AnyLoc#3]
HI, thanks for you great work, but would you release the vlad parameter in the paper ,I think download all the dataset is hard for everyone to generate the vlad cluster. thanks.

**Comment by TheProjectsGuy** [comment]
Hey @ghoshaw ,
We’re in the process of releasing the VLAD cluster centers (along with other things that we can make public) soon. It should be up in a few days. Thanks for pointing this out.

**Comment by ghoshaw** [comment]
ok, thanks and look forward to it!
