### ISSUE TITLE
Use of project

### ISSUE THREAD

**Issue by zs001122** [AnyLoc/AnyLoc#31]
Hello! How can I apply my own data

**Comment by TheProjectsGuy** [comment]
Hey @zs001122,

Thanks for taking interest in our work. I guess you want to apply our method on your own dataset. There are multiple interpretations of this question

1. Inference on custom dataset (most common): You just want global descriptors using one of the AnyLoc domains (vocabulary). I suggest using `torch.hub` model for this. Refer to https://github.com/AnyLoc/AnyLoc/issues/11#issuecomment-1783870144 for more on this.
2. Custom vocabulary: You want to train anyloc from scratch (fit VLAD descriptors) on your own dataset. I'd suggest looking at this: https://github.com/AnyLoc/AnyLoc/issues/22#issuecomment-1840750967

You can refer to this comment for more information on "vocabulary": https://github.com/AnyLoc/AnyLoc/issues/26#issuecomment-1983376300
