### ISSUE TITLE
File is not a zip file

### ISSUE THREAD

**Issue by ovysotska** [AnyLoc/AnyLoc#33]
Hey everyone,

I am trying to run 
`python ./anyloc_vlad_generate.py --in-dir <path_to_images> --imgs-ext jpg --out-dir <path_to_output> --domain urban
` 
locally and I am running into issue when downloading the `cache.zip`.

```
... raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

And this cache seems to be important to use the rest of the code.
Have you seen this problem before?
Thanks!

**Comment by paolovic** [comment]
same here

where you able to resolve it @ovysotska ?

It seems like the link that provides the cached files is broken
https://iiitaphyd-my.sharepoint.com/:u:/g/personal/avneesh_mishra_research_iiit_ac_in/EW-ZqUeWWexNhbLEQvsCk2wBeucxNlhEpsfeUHHOreyLag

**Comment by TheProjectsGuy** [comment]
Hey there, if you're getting this error in `onedrivedownloader`, then it could be because of our OneDrive link breaking. We're working on it. I request you to see [this comment](https://github.com/AnyLoc/AnyLoc/issues/34#issuecomment-2162492086) in the meanwhile.
