### ISSUE TITLE
Downloading cache.zip

### ISSUE THREAD

**Issue by boni-hu** [AnyLoc/AnyLoc#35]
I am currently facing an issue downloading the cache.zip file locally, which appears to be crucial for the remaining code to function properly. I eagerly await your response.

Thank you,
Boni

**Comment by paolovic** [comment]
see #33

**Comment by TheProjectsGuy** [comment]
Hey there, if you're getting this error in `onedrivedownloader`, then it could be because of our OneDrive link breaking. We're working on it. I request you to see [this comment](https://github.com/AnyLoc/AnyLoc/issues/34#issuecomment-2162492086) in the meanwhile.

**Comment by TheProjectsGuy** [comment]
Also, if you want to use our codebase for benchmarking using your own dataset, I suggest you have a look at #31 and #11.

**Comment by boni-hu** [comment]
@TheProjectsGuy Many thanks! I'll try using my own dataset.
