### ISSUE TITLE
Example code of VPair

### ISSUE THREAD

**Issue by PHChenGit** [AnyLoc/AnyLoc#36]
Hi,

Is there some example codes that shows how to use AnyLoc to find the most similar image between drone query image and referenced iamge? I am new to this domain, and I am trying to reproduce your VPair demo video.
If you can show some examples that will be a great help to me.

Thanks.

**Comment by huhulike** [comment]
I have the same question and look forward to the author's reply

**Comment by TheProjectsGuy** [comment]
Hey @PHChenGit @huhulike,

Thanks for your interest in our work.
If you're talking about the positioning effect in the demo video, you can look at https://github.com/AnyLoc/AnyLoc/issues/9 where that is discussed.
If you want to use our work on your own dataset, you can have a look at #22 where it's discussed how to use these methods on a custom dataset. Most of the times, if you want to create global/image descriptors, our `torch.hub` release should be more suitable for your requirements (see #11 for that).
