### ISSUE TITLE
dataset avalible?

### ISSUE THREAD

**Issue by GyoungTaeChae** [AnyLoc/AnyLoc#38]
hello, i want to try some codes in this repo.
however, when i click dataset link , it's all empty space 
how can i download datset? 

thankyou!

**Comment by TheProjectsGuy** [comment]
Hey there, thanks for your interest in our work.
We're currently experiencing issues with Microsoft OneDrive. It's available on Dropbox through [here](https://www.dropbox.com/scl/fi/dhyv4k932lxlbdygkolkf/AnyLoc2023-Public-Data.tar.gz?rlkey=8onlj7iezbiw0in1iul8breql&st=tjrn4vn9&dl=0). The documentation and codebase will be updated with this soon.

Meanwhile, you can have a look at [documentation label](https://github.com/AnyLoc/AnyLoc/issues?q=label%3Adocumentation+) for more information on how to use the codebase.

**Comment by GyoungTaeChae** [comment]
> Hey there, thanks for your interest in our work. We're currently experiencing issues with Microsoft OneDrive. It's available on Dropbox through [here](https://www.dropbox.com/scl/fi/dhyv4k932lxlbdygkolkf/AnyLoc2023-Public-Data.tar.gz?rlkey=8onlj7iezbiw0in1iul8breql&st=tjrn4vn9&dl=0). The documentation and codebase will be updated with this soon.
> 
> Meanwhile, you can have a look at [documentation label](https://github.com/AnyLoc/AnyLoc/issues?q=label%3Adocumentation+) for more information on how to use the codebase.

really appreciate your reply, as i beginner of github, i couldn't check documentation label. Thank you !

**Comment by oravus** [comment]
Hope you were able to download the dataset and use the codebase. Please feel free to reopen otherwise. Cheers!
