### ISSUE TITLE
Question about VP_AIR Dataset and Table 4 results.

### ISSUE THREAD

**Issue by euncheolChoi** [AnyLoc/AnyLoc#5]
Thank you for sharing your great work.
I have a quetion about  vpair_gt.npy file and Experiment results(Table4).

< Question 1 > 
I want to use the dino_v2_vlad.py code to check the recall results for the VPAir dataset, but VP-Air dataset does not provide the vpair_gt.npy file. 
How can I get this file? 

./VPAir
├── [ 677] camera_calibration.yaml
├── [420K] distractors [10000 entries exceeds filelimit, not opening dir]
├── [4.0K] distractors_temp
├── [ 321] License.txt
├── [177K] poses.csv
├── [ 72K] queries [2706 entries exceeds filelimit, not opening dir]
├── [160K] reference_views [2706 entries exceeds filelimit, not opening dir] ├── [ 96K] poses.csv
├── [ 96K] reference_views_npy [2706 entries exceeds filelimit, not opening dir] ├── [ 96K] reference_views_npy [2706 entries exceeds filelimit, not opening dir] â
**└── [ 82K] vpair_gt.npy**

< Question 2 > 
In Table 4, the results of calculating the recall using Dinov2 are presented.  Since the VLAD layer is not used here, I wonder how the recall result was obtained by processing the features obtained by the Dino feature extractor.

**Comment by TheProjectsGuy** [comment]
Hey @euncheolChoi,

Thanks for your interest in our work. 

> Q1: vpair_gt.npy file

Note that the datasets (that we can disclose at the moment) are present in the public material. Most of these are structured environment datasets. The original VPAir dataset can be requested from [AerVisLoc/vpair](https://github.com/AerVisLoc/vpair). You can also download a copy (containing the `vpair_gt.npy`) from our [public files](https://iiitaphyd-my.sharepoint.com/:f:/g/personal/avneesh_mishra_research_iiit_ac_in/Ek6y97czRqRIgIrd4Yj2_aYBz02Nkvmdbh_9Ec_-HgMSHw). 

> Q2: Table-4 in paper: What gave the recall values for DINOv2

As described in section 5 of our paper, the CLS token was used as the global representation of the input image. So the numbers for [DINO](https://github.com/AnyLoc/AnyLoc/blob/main/scripts/dino_global_vpr.py) and [DINOv2](https://github.com/AnyLoc/AnyLoc/blob/main/scripts/dino_v2_global_vpr.py) (not the AnyLoc ones) are calculated by using the CLS tokens.

**Comment by TheProjectsGuy** [comment]
Linking [this](https://github.com/AnyLoc/AnyLoc/issues/8#issuecomment-1712450557) for context.
